const NotificationTypes = {
  TEST: "TEST",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_SHIPPED: "ORDER_SHIPPED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_CANCELED: "ORDER_CANCELED",
  PRODUCT_BACK_IN_STOCK: "PRODUCT_BACK_IN_STOCK",
  PRICE_DROP: "PRICE_DROP",
  REVIEW_REMINDER: "REVIEW_REMINDER",
  NEW_ORDER: "NEW_ORDER",
};

module.exports = NotificationTypes;
